"use client";
import * as Dialog from "@radix-ui/react-dialog";
import Image from "next/image";
import Link from "next/link";
import { Building2, LoaderCircle, MapPin, Phone, UserRound, X } from "lucide-react";
import { useProfilePreview } from "@/hooks/use-messaging";

function label(value: string) { return value ? value.split("-").map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" ") : "Seller"; }
export function ProfilePreviewModal({ userId, open, onOpenChange }: { userId: number | null; open: boolean; onOpenChange: (open: boolean) => void }) {
  const profile = useProfilePreview(userId, open);
  return <Dialog.Root onOpenChange={onOpenChange} open={open}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-[110] bg-slate-950/45 backdrop-blur-[2px] data-[state=open]:animate-in data-[state=closed]:animate-out"/><Dialog.Content aria-describedby="profile-preview-description" className="fixed bottom-0 left-0 z-[111] w-full rounded-t-3xl bg-white p-6 shadow-2xl outline-none sm:bottom-auto sm:left-1/2 sm:top-1/2 sm:max-w-md sm:-translate-x-1/2 sm:-translate-y-1/2 sm:rounded-2xl">
    <div className="flex items-center justify-between"><Dialog.Title className="text-lg font-bold text-[#0b1426]">Profile preview</Dialog.Title><Dialog.Close aria-label="Close profile preview" className="grid size-9 place-items-center rounded-lg text-[#66758d] hover:bg-slate-100"><X className="size-5"/></Dialog.Close></div>
    {profile.isLoading ? <div className="grid min-h-64 place-items-center"><LoaderCircle className="size-7 animate-spin text-[#0864ff]"/></div> : profile.isError ? <div className="py-16 text-center"><p className="font-semibold text-[#0b1426]">Profile unavailable</p><p className="mt-2 text-sm text-[#66758d]">{profile.error.message}</p></div> : profile.data ? <div className="mt-5"><div className="flex items-center gap-4"><div className="relative grid size-20 shrink-0 place-items-center overflow-hidden rounded-full bg-blue-50 text-[#65758d]">{profile.data.profilePhotoUrl ? <Image alt={`${profile.data.displayName} profile`} className="object-cover" fill sizes="80px" src={profile.data.profilePhotoUrl} unoptimized/> : <UserRound className="size-11 stroke-[1.4]"/>}</div><div className="min-w-0"><h2 className="truncate text-xl font-bold text-[#0b1426]">{profile.data.displayName}</h2><p className="mt-1 text-sm font-medium text-[#0864ff]">{label(profile.data.businessType || profile.data.roleLabel)}</p>{profile.data.companyName ? <p className="mt-1 flex items-center gap-1.5 truncate text-sm text-[#66758d]"><Building2 className="size-4"/>{profile.data.companyName}</p> : null}</div></div>
      <p className="mt-5 line-clamp-3 text-sm leading-6 text-[#5f6e84]" id="profile-preview-description">{profile.data.bioExcerpt || `${profile.data.displayName} is a marketplace member.`}</p><div className="mt-4 space-y-2 text-sm text-[#52627a]">{profile.data.city || profile.data.country ? <p className="flex items-center gap-2"><MapPin className="size-4"/>{[profile.data.city, profile.data.country].filter(Boolean).join(", ")}</p> : null}{profile.data.phone ? <p className="flex items-center gap-2"><Phone className="size-4"/>{profile.data.phone}</p> : null}</div><Link className="mt-6 inline-flex h-11 w-full items-center justify-center rounded-xl bg-[#0864ff] text-sm font-semibold text-white hover:bg-[#0757dc]" href={profile.data.publicProfileUrl}>View Profile</Link></div> : null}
  </Dialog.Content></Dialog.Portal></Dialog.Root>;
}
